services:
  muse:
    image: ghcr.io/museofficial/muse:latest
    restart: always
    volumes:
      - /mnt/user/appdata/muse:/data
    environment:
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_USER_ID=${DISCORD_USER_ID}      # Discord user ID of the user you want Aoede to follow
      - SPOTIFY_BOT_AUTOPLAY=true  # Autoplay similar songs when your music ends (true/false)
      - SPOTIFY_DEVICE_NAME="djpeg"