# Docker Compose configuration for Jellyfin - Media server
services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/user/appdata/tsdproxy/data:/data
      - /mnt/user/appdata/tsdproxy/config:/config
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped


  # Jellyfin - Media server for movies, TV shows and music
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=99
      - PGID=100
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/user/appdata/jellyfin/config:/config
      - /mnt/user/media/:/media
      - "/etc/localtime:/etc/localtime:ro"
      - "/tmp:/transcode"
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "jellyfin"
      # HTTPS on 443 -> container port 8096 (HTTP)
      tsdproxy.port.1: "443/https:8096/http, tailscale_funnel"
    restart: unless-stopped
    devices:
        - /dev/dri/card0:/dev/dri/card0
        - /dev/dri/renderD128:/dev/dri/renderD128


  arch-seerr:
        ports:
            - 5055:5055
        container_name: seerr
        volumes:
            - /mnt/user/appdata/seerr/config:/config
            - /etc/localtime:/etc/localtime:ro
        environment:
            - UMASK=000
            - PUID=99
            - PGID=100
        image: binhex/arch-seerr
        labels:
          tsdproxy.enable: "true"
          tsdproxy.name: "seerr"
          # HTTPS on 443 -> container port 5055 (HTTP)
          tsdproxy.port.1: "443/https:5055/http, tailscale_funnel"

  # Jfa-Go - Docker service
  jfa-go:
    container_name: jfa-go
    hostname: jfa-go
    restart: unless-stopped
    volumes:
      - '/mnt/user/appdata/jfa-go:/data'
      - '/mnt/user/appdata/jellyfin/config:/jf'
      - '/etc/localtime:/etc/localtime:ro'
    image: hrfee/jfa-go
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "invite"
      # HTTPS on 443 -> container port 8056 (HTTP)
      tsdproxy.port.1: "443/https:8056/http, tailscale_funnel"