# Docker Compose configuration for Jellyfin - Media server

services:
  # Jellyfin - Media server for movies, TV shows and music
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    hostname: jellyfin_host
    environment:
      - PUID=99
      - PGID=100
      - TZ=America/Los_Angeles
     # - JELLYFIN_PublishedServerUrl="https://jellyfin.{DOMAIN}" #optional
    volumes:
      - /mnt/user/appdata/jellyfin/config:/config
      - /mnt/user/media/:/media
      - "/etc/localtime:/etc/localtime:ro"
      - "/tmp:/transcode"

    ports:
      - 8096:8096
      - 8920:8920 #optional
    restart: unless-stopped
    devices:
        - /dev/dri/card0:/dev/dri/card0
        - /dev/dri/renderD128:/dev/dri/renderD128


  #seerr - Content request management for Jellyfin
  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    init: true
    container_name: seerr
    hostname: seerr_host
    user: "99:100"
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Los_Angeles
    ports:
      - 5055:5055
    volumes:
      - /mnt/user/appdata/config/seerr:/app/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    restart: unless-stopped


  # Jfa-Go - Docker service
  jfa-go:
    container_name: jfa-go
    hostname: jfa-go_host
    restart: unless-stopped
    ports:
      - '8056:8056'
      - '8057:8057'
    volumes:
      - '/mnt/user/appdata/jfa-go:/data'
      - '/mnt/user/appdata/jellyfin/config:/jf'
      - '/etc/localtime:/etc/localtime:ro'
    image: hrfee/jfa-go
