services:
  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    hostname: searxng
    networks:
      - search
    ports:
      - "8089:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
      - UWSGI_WORKERS=${SEARXNG_UWSGI_WORKERS:-4}
      - UWSGI_THREADS=${SEARXNG_UWSGI_THREADS:-4}
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
  redis:
    container_name: redis
    hostname: redis
    image: docker.io/valkey/valkey:8-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    networks:
      - search
    volumes:
      - valkey-data2:/data
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  farfalle:
    image: ghcr.io/rashadphz/farfalle:main
    container_name: farfalle
    restart: unless-stopped
    environment:
        - OLLAMA_API_BASE=${OLLAMA_API_BASE:-http://ollama:11434}
        - ENABLE_LOCAL_MODELS=True
        - NEXT_PUBLIC_LOCAL_MODE_ENABLED=True
        - NEXT_PUBLIC_PRO_MODE_ENABLED=True
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        - SEARCH_PROVIDER=searxng
        - SEARXNG_BASE_URL=${SEARXNG_BASE_URL:-http://searxng:8089}
        - TAVILY_API_KEY=${TAVILY_API_KEY}
        - CUSTOM_MODEL=${CUSTOM_MODEL:-mistral-nemo:12b}
    ports:
        - 63278:8000
        - 27374:3000
    depends_on:
        - ollama
        - searxng
    networks:
        - search
  ollama:
        image: ollama/ollama
        container_name: ollama
        hostname: ollama
        networks:
          - search
        ports:
            - '11434:11434'
        volumes:
            - '/mnt/user/appdata/ollama:/root/.ollama'
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [ gpu ]
networks:
  search:

volumes:
  valkey-data2: