services:
  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    hostname: searxng
    networks:
      - search
    ports:
      - "8089:8080"
    volumes:
      - /mnt/user/appdata/searxng/:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
      - UWSGI_WORKERS=${SEARXNG_UWSGI_WORKERS:-4}
      - UWSGI_THREADS=${SEARXNG_UWSGI_THREADS:-4}
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  ollama:
        image: ollama/ollama
        container_name: ollama
        hostname: ollama
        networks:
          - search
        ports:
            - '11434:11434'
        volumes:
            - '/mnt/user/appdata/ollama:/root/.ollama'
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [ gpu ]

  web:
    image: ghcr.io/hoarder-app/hoarder:${HOARDER_VERSION:-release}
    restart: unless-stopped
    volumes:
      - /mnt/user/appdata/hoarder/web/data:/data
    networks:
      - search
    
    ports:
      - 3000:3000
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      DATA_DIR: /data
      OLLAMA_BASE_URL: http://ollama:11434
      INFERENCE_TEXT_MODEL: llama3.2:3b
      INFERENCE_IMAGE_MODEL: minicpm-v:8b
      INFERENCE_CONTEXT_LENGTH: 16384
      MAX_ASSET_SIZE_MB: 20
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
      NEXTAUTH_URL: ${NEXTAUTH_URL}


  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
  meilisearch:
    image: getmeili/meilisearch:v1.11.1
    restart: unless-stopped
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - /mnt/user/appdata/hoarder/meilisearch/meili_data:/meili_data

volumes:
  meilisearch:
  data:

networks:
  search:
