version: "3.3"
services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft-fabric
    hostname: minecraft_host
    ports:
      - 25567:25567
      - 8100:8100
    volumes:
      - "/home/jbpixel/Docker/minecraftfabricserver:/data"
    tty: true
    stdin_open: true
    environment:
      UID: 99
      GUID: 100
      TYPE: FABRIC
      FABRIC_LOADER_VERSION: 0.15.7
      MAX_TICK_TIME: -1
      LEVEL: "New World"
      VERSION: 1.20.1
      PVP: "TRUE"
      ALLOW_FLIGHT: "TRUE"
      EULA: "TRUE"
      DIFFICULTY: "normal"
      MAX_PLAYERS: 8
      MAX_WORLD_SIZE: 300000
      SYNC_CHUNK_WRITES: FALSE
      JVM_OPTS: -XX:+UseZGC -XX:AllocatePrefetchStyle=1 -XX:-ZProactive
      ALLOW_NETHER: "TRUE"
      TZ: "America/Los_Angeles"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "TRUE"
      ENABLE_COMMAND_BLOCK: "TRUE"
      GENERATE_STRUCTURES: "TRUE"
      VIEW_DISTANCE: 16
      SIMULATION_DISTANCE: 7
      OPS: user
      MAX_BUILD_HEIGHT: 256
      SPAWN_PROTECTION: 1
      MODE: survival
      MOTD: "§c§lFeliz Jueves!"
      INIT_MEMORY: 4G
      MAX_MEMORY: 12G
      SERVER_PORT: 25567
      CONSOLE: "FALSE"
      GUI: "FALSE"
      ICON: ""
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 1
      resources:
        limits:
          memory: 12G
        reservations:
          memory: 5G

    healthcheck:
      test: ["CMD", "/bin/check-health"]
      start_period: 3m
      interval: 20s
      timeout: 5s