services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    hostname: minecraft
    ports:
      - 25567:25567
    volumes:
      - "/mnt/user/appdata/minecraft/:/data/"
    tty: true
    stdin_open: true
    environment:
      TYPE: NEOFORGE
      VERSION: "1.21.1"
      NEOFORGE_VERSION: "21.1.194"
      MAX_TICK_TIME: -1
      ENABLE_AUTOPAUSE: "TRUE"
      AUTOPAUSE_TIMEOUT_INIT: "600"
      AUTOPAUSE_TIMEOUT_EST: "400"
      # USE_MODPACK_START_SCRIPT: "FALSE"
      PVP: "TRUE"
      ALLOW_FLIGHT: "TRUE"
      EULA: "TRUE"
      DIFFICULTY: "hard"
      MAX_PLAYERS: 8
      MAX_WORLD_SIZE: 300000
      SEED: 1
      USE_AIKAR_FLAGS: "FALSE"
      ALLOW_NETHER: "TRUE"
      TZ: "America/Los_Angeles"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "TRUE"
      ENABLE_COMMAND_BLOCK: "TRUE"
      GENERATE_STRUCTURES: "TRUE"
      VIEW_DISTANCE: 10
      OPS: user
      SPAWN_PROTECTION: 1
      MODE: survival
      MEMORY: 8G
      JVM_XX_OPTS: -XX:+UseG1GC -XX:MaxGCPauseMillis=130 -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=28 -XX:G1HeapRegionSize=16M -XX:G1ReservePercent=20 -XX:G1MixedGCCountTarget=3 -XX:InitiatingHeapOccupancyPercent=10 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=0 -XX:SurvivorRatio=32 -XX:MaxTenuringThreshold=1 -XX:G1SATBBufferEnqueueingThresholdPercent=30 -XX:G1ConcMarkStepDurationMillis=5.0 -XX:G1ConcRefinementServiceIntervalMillis=150 -XX:G1ConcRSHotCardLimit=16 -XX:AllocatePrefetchStyle=3
      MOTD: "§c§l2025!"
      SERVER_PORT: 25567
      CONSOLE: "FALSE"
      GUI: "FALSE"
      SIMULATION_DISTANCE: 10
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 3
      resources:
        limits:
          memory: 12G
        reservations:
          memory: 10G

    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 30s
      timeout: 5s