services:
  minecraftforge:
    image: itzg/minecraft-server
    container_name: minecraftforge
    hostname: minecraftforge
    ports:
      - 25567:25567
    volumes:
      - "/home/jbpixel/Docker/beach_house_25/:/data/"
    tty: true
    stdin_open: true
    environment:
      UID: 99
      GUID: 100
      TYPE: FORGE
      FORGE_VERSION: 47.3.10
      MAX_TICK_TIME: -1
      ENABLE_AUTOPAUSE: "TRUE"
      AUTOPAUSE_TIMEOUT_INIT: "600"
      AUTOPAUSE_TIMEOUT_EST: "400"
      # USE_MODPACK_START_SCRIPT: "FALSE"
      VERSION: 1.120.1
      PVP: "TRUE"
      ALLOW_FLIGHT: "TRUE"
      EULA: "TRUE"
      DIFFICULTY: "hard"
      MAX_PLAYERS: 8
      MAX_WORLD_SIZE: 300000
      USE_AIKAR_FLAGS: "TRUE"
      ALLOW_NETHER: "TRUE"
      TZ: "America/Los_Angeles"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "TRUE"
      ENABLE_COMMAND_BLOCK: "TRUE"
      GENERATE_STRUCTURES: "TRUE"
      VIEW_DISTANCE: 20
      OPS: user
      MAX_BUILD_HEIGHT: 256
      SPAWN_PROTECTION: 1
      MODE: survival
      MOTD: "§c§lFeliz Jueves!"
      # INIT_MEMORY: 5G
      MAX_MEMORY: 10
      SERVER_PORT: 25567
      CONSOLE: "FALSE"
      GUI: "FALSE"
      SIMULATION_DISTANCE: 8
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 3
      resources:
        limits:
          memory: 12G
        reservations:
          memory: 10G

    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 10s
      timeout: 3s