services:
  minecraft:
    image: itzg/minecraft-server
    container_name: createmon
    hostname: minecraft
    ports:
      - 25567:25567
    volumes:
      - "/home/jbpixel/Docker/createmon/:/data/"
    tty: true
    stdin_open: true
    environment:
      UID: 99
      GUID: 100
      TYPE: NEOFORGE
      VERSION: "1.21.1"
      NEOFORGE_VERSION: 21.1.141
      MAX_TICK_TIME: -1
      ENABLE_AUTOPAUSE: "TRUE"
      AUTOPAUSE_TIMEOUT_INIT: "600"
      AUTOPAUSE_TIMEOUT_EST: "400"
      # USE_MODPACK_START_SCRIPT: "FALSE"
      PVP: "TRUE"
      ALLOW_FLIGHT: "TRUE"
      EULA: "TRUE"
      DIFFICULTY: "hard"
      MAX_PLAYERS: 6
      MAX_WORLD_SIZE: 300000
      SEED: 5868800201184252347
      #USE_AIKAR_FLAGS: "TRUE"
      ALLOW_NETHER: "TRUE"
      TZ: "America/Los_Angeles"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "TRUE"
      ENABLE_COMMAND_BLOCK: "TRUE"
      GENERATE_STRUCTURES: "TRUE"
      VIEW_DISTANCE: 18
      OPS: user
      SPAWN_PROTECTION: 1
      MODE: survival
      MEMORY: 10G
      JVM_XX_OPTS: -XX:+UseG1GC -XX:MaxGCPauseMillis=130 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=28 -XX:G1HeapRegionSize=16M -XX:G1ReservePercent=20 -XX:G1MixedGCCountTarget=3 -XX:InitiatingHeapOccupancyPercent=10 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=0 -XX:SurvivorRatio=32 -XX:MaxTenuringThreshold=1 -XX:G1SATBBufferEnqueueingThresholdPercent=30 -XX:G1ConcMarkStepDurationMillis=5 -XX:G1ConcRSHotCardLimit=16 -XX:G1ConcRefinementServiceIntervalMillis=150
      MOTD: "§c§l2025!"
      SERVER_PORT: 25567
      CONSOLE: "FALSE"
      GUI: "FALSE"
      SIMULATION_DISTANCE: 10
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 3
      resources:
        limits:
          memory: 18G
        reservations:
          memory: 16G

    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 30s
      timeout: 5s