services:
  glance:
    container_name: glance
    user: 99:100
    image: glanceapp/glance
    hostname: glance
    volumes:
      - /mnt/user/appdata/glance/config:/app/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8885:8080
    restart: unless-stopped