# Docker Compose configuration for Arr Stack - Radarr, Sonarr, Bazarr (media management)

services:
  # Radarr - Movie collection manager and downloader
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    hostname: radarr
    tty: true
    stdin_open: true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/appdata/radarr:/config
      - /mnt/storage/movies:/movies
      - /mnt/storage/downloads:/downloads
    restart: unless-stopped
    #ports:
    #  - 7878:7878
    networks: [arr]
    labels:
      - "docktail.service.enable=true"
      - "docktail.service.name=radarr"
      - "docktail.service.port=7878"
      - "docktail.service.network=arr"


  # Sonarr - TV series collection manager and downloader
  sonarr:
    container_name: sonarr
    hostname: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    volumes:
      - /mnt/appdata/sonarr:/config
      - /mnt/storage/tvshows:/tvshows
      - /mnt/storage/anime:/anime
      - /mnt/storage/downloads:/downloads

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    #ports:
    #- 8989:8989
    networks: [arr]
    labels:
      - "docktail.service.enable=true"
      - "docktail.service.name=sonarr"
      - "docktail.service.port=8989"
      - "docktail.service.network=arr"

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    hostname: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/appdata/prowlarr:/config
    #ports:
    # - 9696:9696
    networks: [arr]
    restart: unless-stopped
    labels:
      - "docktail.service.enable=true"
      - "docktail.service.name=prowlarr"
      - "docktail.service.port=9696"
      - "docktail.service.network=arr"

  # Flaresolverr - Docker service
  flaresolverr:
    image: "ghcr.io/flaresolverr/flaresolverr:latest"
    container_name: flaresolverr
    hostname: flaresolverr
    restart: unless-stopped
    environment:
      - LOG_LEVEL=info
      - PUID=1000
      - PGID=1000
    ports:
      - "8191:8191"
    networks: [arr]

  # Lidarr - Docker service
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/appdata/lidarr/config:/config
      - /mnt/storage/music:/music #optional
      - /mnt/downloads:/downloads #optional
    networks: [arr]
    #ports:
    #- 8686:8686
    restart: unless-stopped
    labels:
      - "docktail.service.enable=true"
      - "docktail.service.name=lidarr"
      - "docktail.service.port=8686"
      - "docktail.service.network=arr"

  # Recyclarr - Docker service
  profilarr:
    image: ghcr.io/dictionarry-hub/profilarr:latest
    container_name: profilarr
    #ports:
    # - '6868:6868'
    volumes:
      - /mnt/appdata/profilarr:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      # Uncomment ORIGIN if you use a reverse proxy to access your containers.
      - ORIGIN=https://profilarr.java-regulus.ts.net
      - PARSER_HOST=parser
      - PARSER_PORT=5000
    depends_on:
      parser:
        condition: service_healthy
    labels:
      - "docktail.service.enable=true"
      - "docktail.service.name=profilarr"
      - "docktail.service.port=6868"
  # Optional - only needed for CF/QP testing
  parser:
    image: ghcr.io/dictionarry-hub/profilarr-parser:latest
    container_name: profilarr-parser
    expose:
      - "5000"

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    hostname: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - WEBUI_PORT=8888
      - DOCKER_MODS=ghcr.io/vuetorrent/vuetorrent-lsio-mod:latest
    volumes:
      - /mnt/appdata/qbittorrent/config:/config/
      - /mnt/storage/downloads:/downloads
      - /mnt/storage/anime:/anime
      - /mnt/storage/music:/music

      - /mnt/storage/movies:/movies
      - /mnt/storage/tvshows:/tvshows
    ports:
      #- 8888:8888
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks: [arr]
    labels:
      - "docktail.service.enable=true"
      - "docktail.service.name=qbittorrent"
      - "docktail.service.port=8888"
      - "docktail.service.network=arr"

networks:
  # Arr - Docker service
  arr:
    name: arr
