version: '3.3'
services:
  # Komga - Manga server
  komga:
    image: gotson/komga
    container_name: komga
    hostname: komga
    volumes:
      - /mnt/user/comics_share/:/comics
      - /mnt/user/appdata/komga:/config
      - /mnt/user/comics_share/BOOKS/:/books
    user: "99:100"
    environment:
      - TZ="America/Los_Angeles"
    restart: unless-stopped
    ports:
      - 25600:25600
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "4gb"
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "komga"
      # HTTPS on 443 -> container port 8585 (HTTP)
      tsdproxy.port.1: "443/https:25600/http"

  # Mylar3 - Docker service
  mylar3:
    image: lscr.io/linuxserver/mylar3:latest
    container_name: mylar3
    hostname: mylar
    environment:
      - PUID=99
      - PGID=100
    volumes:
      - /mnt/user/appdata/mylar:/config
      - /mnt/user/comics_share/COMICS:/comics
      - /mnt/user/media_cache/downloads/mylar:/downloads
    ports:
      - 8090:8090
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "3gb"
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "mylar"
      # HTTPS on 443 -> container port 8090 (HTTP)
      tsdproxy.port.1: "443/https:8090/http, tailscale_funnel"