version: "3.9"

services:
  app:
    image: ghcr.io/gabe565/castsponsorskip
    environment:
      TZ: America/Los_Angeles
      # CSS_PAUSED_INTERVAL:
      # CSS_PLAYING_INTERVAL:
      # CSS_CATEGORIES:
      # CSS_YOUTUBE_API_KEY:
      # CSS_MUTE_ADS:
    network_mode: host
    restart: always
  piped-frontend:
        image: 1337kavin/piped-frontend:latest
        restart: unless-stopped
        ports:
          -88887:80
        depends_on:
            - piped
        environment:
            BACKEND_HOSTNAME: BACKEND_HOSTNAME_PLACEHOLDER
            HTTP_MODE: HTTP_MODE_PLACEHOLDER
        container_name: piped-frontend
    piped-proxy:
        image: 1337kavin/piped-proxy:latest
        restart: unless-stopped
        ports:
          -88885:80
        environment:
            - UDS=1
        volumes:
            - piped-proxy:/app/socket
        container_name: piped-proxy
    piped:
        image: 1337kavin/piped:latest
        restart: unless-stopped
        ports:
          -88886:80
        volumes:
            - ./config/config.properties:/app/config.properties:ro
        depends_on:
            - postgres
        container_name: piped-backend

    postgres:
        image: pgautoupgrade/pgautoupgrade:16-alpine
        restart: unless-stopped
        volumes:
            - /mnt/user/appdata/piped/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=piped
            - POSTGRES_USER=piped
            - POSTGRES_PASSWORD=changeme
        container_name: postgres

volumes:
    piped-proxy: null