services:
  immich:
    image: ghcr.io/imagegenius/immich:latest
    container_name: immich
    environment:
      - PUID=99
      - PGID=100
      - TZ=America/Los_Angeles
      - DB_HOSTNAME=192.168.1.x
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=localhost
      - DB_PORT=5432 #optional
      - DOCKER_MODS=imagegenius/mods:universal-redis
      - REDIS_PORT=6379 #optional
      - REDIS_PASSWORD= #optional
      - SERVER_HOST=0.0.0.0 #optional
      - SERVER_PORT=8080 #optional
      - MACHINE_LEARNING_HOST=0.0.0.0 #optional
      - MACHINE_LEARNING_PORT=3003 #optional
      - MACHINE_LEARNING_WORKERS=1 #optional
      - MACHINE_LEARNING_WORKER_TIMEOUT=120 #optional
    volumes:
      - /mnt/user/appdata/immich:/config
      - /mnt/user/media/PHOTOS:/photos
      - /mnt/user/media/PHOTOS/upload/library:/libraries #optional
      - model-cache:/cache
    devices:
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/renderD128:/dev/dri/renderD128
    ports:
      - 2283:8080
    restart: unless-stopped

# This container requires an external application to be run separately.
# By default, ports for the databases are opened, be careful when deploying it
# Valkey:
  valkey:
    image: valkey/valkey:8-bookworm
    ports:
      - 6379:6379
    container_name: valkey
# PostgreSQL 14:
  postgres14:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    ports:
      - 5432:5432
    container_name: postgres14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: immich
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
      # DB_STORAGE_TYPE: 'HDD'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  # Pgdata - Docker service
  pgdata:
  # Model-Cache - Docker service
  model-cache:
