# Docker Compose configuration for Immich - Photo and video backup

version: "3.8"
services:
  # Immich-Server - Docker service
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # command: ["start.sh", "immich"] REmoved as of v1.106.0
    volumes:
      - /mnt/user/media/PHOTOS/upload:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    environment:
      - UPLOAD_LOCATION=/usr/src/app/upload
      - IMMICH_VERSION=2.5.6
      - DB_PASSWORD=postgres
      - DB_HOSTNAME=immich_postgres
      - DB_USERNAME=postgres
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=immich_redis
      - TYPESENSE_ENABLED=false
      - TYPESENSE_API_KEY=random_text
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    devices:
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/renderD128:/dev/dri/renderD128
    # deploy: # Uncomment this section if using NVIDIA GPU
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           capabilities: [gpu, video, compute]
    restart: always
    healthcheck:
      disable: false

  # Immich-Machine-Learning - Docker service
  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    restart: always
    environment:
      - UPLOAD_LOCATION=/mnt/user/appdata/immich/upload
      - IMMICH_VERSION=release
      - DB_PASSWORD=postgres
      - DB_HOSTNAME=immich_postgres
      - DB_USERNAME=postgres
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=immich_redis
    devices:
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/renderD128:/dev/dri/renderD128
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           capabilities:
    #             - gpu
    #             - compute
    #             - video
  # Redis - In-memory data structure store
  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:9
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  # Database - Docker service
  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    healthcheck:
      disable: false
volumes:
  # Pgdata - Docker service
  pgdata:
  # Model-Cache - Docker service
  model-cache:
