
services:
  octoprint:
    image: octoprint/octoprint
    restart: unless-stopped
    ports:
      - 8886:80
    # devices:
    # use `python -m serial.tools.miniterm` to see what the name is of the printer, this requires pyserial
    #  - /dev/ttyACM0:/dev/ttyACM0
    #  - /dev/video0:/dev/video0
    volumes:
     - /mnt/user/appdata/octoprint:/octoprint
